! contains( QXPACK_IC, indcom_algor_thr_eigen ) { 
    QXPACK_IC *= indcom_algor_thr_eigen 
    CONFIG *= c++11 
    INCLUDEPATH *= $$PWD/ 

    QXPACK_IC_HEADERS_ALGOR_3RD_EIGEN += \  
        $$PWD/Eigen/Cholesky \ 
        $$PWD/Eigen/CholmodSupport \ 
        $$PWD/Eigen/CMakeLists.txt \ 
        $$PWD/Eigen/Core \ 
        $$PWD/Eigen/Dense \ 
        $$PWD/Eigen/Eigen \ 
        $$PWD/Eigen/Eigenvalues \ 
        $$PWD/Eigen/Geometry \ 
        $$PWD/Eigen/Householder \ 
        $$PWD/Eigen/IterativeLinearSolvers \ 
        $$PWD/Eigen/Jacobi \ 
        $$PWD/Eigen/LU \ 
        $$PWD/Eigen/MetisSupport \ 
        $$PWD/Eigen/OrderingMethods \ 
        $$PWD/Eigen/PardisoSupport \ 
        $$PWD/Eigen/PaStiXSupport \ 
        $$PWD/Eigen/QR \ 
        $$PWD/Eigen/QtAlignedMalloc \ 
        $$PWD/Eigen/Sparse \ 
        $$PWD/Eigen/SparseCholesky \ 
        $$PWD/Eigen/SparseCore \ 
        $$PWD/Eigen/SparseLU \ 
        $$PWD/Eigen/SparseQR \ 
        $$PWD/Eigen/SPQRSupport \ 
        $$PWD/Eigen/StdDeque \ 
        $$PWD/Eigen/StdList \ 
        $$PWD/Eigen/StdVector \ 
        $$PWD/Eigen/SuperLUSupport \ 
        $$PWD/Eigen/SVD \ 
        $$PWD/Eigen/UmfPackSupport \ 
        $$PWD/Eigen/src/Cholesky/LDLT.h \ 
        $$PWD/Eigen/src/Cholesky/LLT.h \ 
        $$PWD/Eigen/src/Cholesky/LLT_LAPACKE.h \ 
        $$PWD/Eigen/src/CholmodSupport/CholmodSupport.h \ 
        $$PWD/Eigen/src/Core/Array.h \ 
        $$PWD/Eigen/src/Core/ArrayBase.h \ 
        $$PWD/Eigen/src/Core/ArrayWrapper.h \ 
        $$PWD/Eigen/src/Core/Assign.h \ 
        $$PWD/Eigen/src/Core/AssignEvaluator.h \ 
        $$PWD/Eigen/src/Core/Assign_MKL.h \ 
        $$PWD/Eigen/src/Core/BandMatrix.h \ 
        $$PWD/Eigen/src/Core/Block.h \ 
        $$PWD/Eigen/src/Core/BooleanRedux.h \ 
        $$PWD/Eigen/src/Core/CommaInitializer.h \ 
        $$PWD/Eigen/src/Core/ConditionEstimator.h \ 
        $$PWD/Eigen/src/Core/CoreEvaluators.h \ 
        $$PWD/Eigen/src/Core/CoreIterators.h \ 
        $$PWD/Eigen/src/Core/CwiseBinaryOp.h \ 
        $$PWD/Eigen/src/Core/CwiseNullaryOp.h \ 
        $$PWD/Eigen/src/Core/CwiseTernaryOp.h \ 
        $$PWD/Eigen/src/Core/CwiseUnaryOp.h \ 
        $$PWD/Eigen/src/Core/CwiseUnaryView.h \ 
        $$PWD/Eigen/src/Core/DenseBase.h \ 
        $$PWD/Eigen/src/Core/DenseCoeffsBase.h \ 
        $$PWD/Eigen/src/Core/DenseStorage.h \ 
        $$PWD/Eigen/src/Core/Diagonal.h \ 
        $$PWD/Eigen/src/Core/DiagonalMatrix.h \ 
        $$PWD/Eigen/src/Core/DiagonalProduct.h \ 
        $$PWD/Eigen/src/Core/Dot.h \ 
        $$PWD/Eigen/src/Core/EigenBase.h \ 
        $$PWD/Eigen/src/Core/ForceAlignedAccess.h \ 
        $$PWD/Eigen/src/Core/Fuzzy.h \ 
        $$PWD/Eigen/src/Core/GeneralProduct.h \ 
        $$PWD/Eigen/src/Core/GenericPacketMath.h \ 
        $$PWD/Eigen/src/Core/GlobalFunctions.h \ 
        $$PWD/Eigen/src/Core/Inverse.h \ 
        $$PWD/Eigen/src/Core/IO.h \ 
        $$PWD/Eigen/src/Core/Map.h \ 
        $$PWD/Eigen/src/Core/MapBase.h \ 
        $$PWD/Eigen/src/Core/MathFunctions.h \ 
        $$PWD/Eigen/src/Core/MathFunctionsImpl.h \ 
        $$PWD/Eigen/src/Core/Matrix.h \ 
        $$PWD/Eigen/src/Core/MatrixBase.h \ 
        $$PWD/Eigen/src/Core/NestByValue.h \ 
        $$PWD/Eigen/src/Core/NoAlias.h \ 
        $$PWD/Eigen/src/Core/NumTraits.h \ 
        $$PWD/Eigen/src/Core/PermutationMatrix.h \ 
        $$PWD/Eigen/src/Core/PlainObjectBase.h \ 
        $$PWD/Eigen/src/Core/Product.h \ 
        $$PWD/Eigen/src/Core/ProductEvaluators.h \ 
        $$PWD/Eigen/src/Core/Random.h \ 
        $$PWD/Eigen/src/Core/Redux.h \ 
        $$PWD/Eigen/src/Core/Ref.h \ 
        $$PWD/Eigen/src/Core/Replicate.h \ 
        $$PWD/Eigen/src/Core/ReturnByValue.h \ 
        $$PWD/Eigen/src/Core/Reverse.h \ 
        $$PWD/Eigen/src/Core/Select.h \ 
        $$PWD/Eigen/src/Core/SelfAdjointView.h \ 
        $$PWD/Eigen/src/Core/SelfCwiseBinaryOp.h \ 
        $$PWD/Eigen/src/Core/Solve.h \ 
        $$PWD/Eigen/src/Core/SolverBase.h \ 
        $$PWD/Eigen/src/Core/SolveTriangular.h \ 
        $$PWD/Eigen/src/Core/StableNorm.h \ 
        $$PWD/Eigen/src/Core/Stride.h \ 
        $$PWD/Eigen/src/Core/Swap.h \ 
        $$PWD/Eigen/src/Core/Transpose.h \ 
        $$PWD/Eigen/src/Core/Transpositions.h \ 
        $$PWD/Eigen/src/Core/TriangularMatrix.h \ 
        $$PWD/Eigen/src/Core/VectorBlock.h \ 
        $$PWD/Eigen/src/Core/VectorwiseOp.h \ 
        $$PWD/Eigen/src/Core/Visitor.h \ 
        $$PWD/Eigen/src/Core/arch/AltiVec/Complex.h \ 
        $$PWD/Eigen/src/Core/arch/AltiVec/MathFunctions.h \ 
        $$PWD/Eigen/src/Core/arch/AltiVec/PacketMath.h \ 
        $$PWD/Eigen/src/Core/arch/AVX/Complex.h \ 
        $$PWD/Eigen/src/Core/arch/AVX/MathFunctions.h \ 
        $$PWD/Eigen/src/Core/arch/AVX/PacketMath.h \ 
        $$PWD/Eigen/src/Core/arch/AVX/TypeCasting.h \ 
        $$PWD/Eigen/src/Core/arch/AVX512/MathFunctions.h \ 
        $$PWD/Eigen/src/Core/arch/AVX512/PacketMath.h \ 
        $$PWD/Eigen/src/Core/arch/CUDA/Complex.h \ 
        $$PWD/Eigen/src/Core/arch/CUDA/Half.h \ 
        $$PWD/Eigen/src/Core/arch/CUDA/MathFunctions.h \ 
        $$PWD/Eigen/src/Core/arch/CUDA/PacketMath.h \ 
        $$PWD/Eigen/src/Core/arch/CUDA/PacketMathHalf.h \ 
        $$PWD/Eigen/src/Core/arch/CUDA/TypeCasting.h \ 
        $$PWD/Eigen/src/Core/arch/Default/ConjHelper.h \ 
        $$PWD/Eigen/src/Core/arch/Default/Settings.h \ 
        $$PWD/Eigen/src/Core/arch/NEON/Complex.h \ 
        $$PWD/Eigen/src/Core/arch/NEON/MathFunctions.h \ 
        $$PWD/Eigen/src/Core/arch/NEON/PacketMath.h \ 
        $$PWD/Eigen/src/Core/arch/SSE/Complex.h \ 
        $$PWD/Eigen/src/Core/arch/SSE/MathFunctions.h \ 
        $$PWD/Eigen/src/Core/arch/SSE/PacketMath.h \ 
        $$PWD/Eigen/src/Core/arch/SSE/TypeCasting.h \ 
        $$PWD/Eigen/src/Core/arch/ZVector/Complex.h \ 
        $$PWD/Eigen/src/Core/arch/ZVector/MathFunctions.h \ 
        $$PWD/Eigen/src/Core/arch/ZVector/PacketMath.h \ 
        $$PWD/Eigen/src/Core/functors/AssignmentFunctors.h \ 
        $$PWD/Eigen/src/Core/functors/BinaryFunctors.h \ 
        $$PWD/Eigen/src/Core/functors/NullaryFunctors.h \ 
        $$PWD/Eigen/src/Core/functors/StlFunctors.h \ 
        $$PWD/Eigen/src/Core/functors/TernaryFunctors.h \ 
        $$PWD/Eigen/src/Core/functors/UnaryFunctors.h \ 
        $$PWD/Eigen/src/Core/products/GeneralBlockPanelKernel.h \ 
        $$PWD/Eigen/src/Core/products/GeneralMatrixMatrix.h \ 
        $$PWD/Eigen/src/Core/products/GeneralMatrixMatrixTriangular.h \ 
        $$PWD/Eigen/src/Core/products/GeneralMatrixMatrixTriangular_BLAS.h \ 
        $$PWD/Eigen/src/Core/products/GeneralMatrixMatrix_BLAS.h \ 
        $$PWD/Eigen/src/Core/products/GeneralMatrixVector.h \ 
        $$PWD/Eigen/src/Core/products/GeneralMatrixVector_BLAS.h \ 
        $$PWD/Eigen/src/Core/products/Parallelizer.h \ 
        $$PWD/Eigen/src/Core/products/SelfadjointMatrixMatrix.h \ 
        $$PWD/Eigen/src/Core/products/SelfadjointMatrixMatrix_BLAS.h \ 
        $$PWD/Eigen/src/Core/products/SelfadjointMatrixVector.h \ 
        $$PWD/Eigen/src/Core/products/SelfadjointMatrixVector_BLAS.h \ 
        $$PWD/Eigen/src/Core/products/SelfadjointProduct.h \ 
        $$PWD/Eigen/src/Core/products/SelfadjointRank2Update.h \ 
        $$PWD/Eigen/src/Core/products/TriangularMatrixMatrix.h \ 
        $$PWD/Eigen/src/Core/products/TriangularMatrixMatrix_BLAS.h \ 
        $$PWD/Eigen/src/Core/products/TriangularMatrixVector.h \ 
        $$PWD/Eigen/src/Core/products/TriangularMatrixVector_BLAS.h \ 
        $$PWD/Eigen/src/Core/products/TriangularSolverMatrix.h \ 
        $$PWD/Eigen/src/Core/products/TriangularSolverMatrix_BLAS.h \ 
        $$PWD/Eigen/src/Core/products/TriangularSolverVector.h \ 
        $$PWD/Eigen/src/Core/util/BlasUtil.h \ 
        $$PWD/Eigen/src/Core/util/Constants.h \ 
        $$PWD/Eigen/src/Core/util/DisableStupidWarnings.h \ 
        $$PWD/Eigen/src/Core/util/ForwardDeclarations.h \ 
        $$PWD/Eigen/src/Core/util/Macros.h \ 
        $$PWD/Eigen/src/Core/util/Memory.h \ 
        $$PWD/Eigen/src/Core/util/Meta.h \ 
        $$PWD/Eigen/src/Core/util/MKL_support.h \ 
        $$PWD/Eigen/src/Core/util/NonMPL2.h \ 
        $$PWD/Eigen/src/Core/util/ReenableStupidWarnings.h \ 
        $$PWD/Eigen/src/Core/util/StaticAssert.h \ 
        $$PWD/Eigen/src/Core/util/XprHelper.h \ 
        $$PWD/Eigen/src/Eigenvalues/ComplexEigenSolver.h \ 
        $$PWD/Eigen/src/Eigenvalues/ComplexSchur.h \ 
        $$PWD/Eigen/src/Eigenvalues/ComplexSchur_LAPACKE.h \ 
        $$PWD/Eigen/src/Eigenvalues/EigenSolver.h \ 
        $$PWD/Eigen/src/Eigenvalues/GeneralizedEigenSolver.h \ 
        $$PWD/Eigen/src/Eigenvalues/GeneralizedSelfAdjointEigenSolver.h \ 
        $$PWD/Eigen/src/Eigenvalues/HessenbergDecomposition.h \ 
        $$PWD/Eigen/src/Eigenvalues/MatrixBaseEigenvalues.h \ 
        $$PWD/Eigen/src/Eigenvalues/RealQZ.h \ 
        $$PWD/Eigen/src/Eigenvalues/RealSchur.h \ 
        $$PWD/Eigen/src/Eigenvalues/RealSchur_LAPACKE.h \ 
        $$PWD/Eigen/src/Eigenvalues/SelfAdjointEigenSolver.h \ 
        $$PWD/Eigen/src/Eigenvalues/SelfAdjointEigenSolver_LAPACKE.h \ 
        $$PWD/Eigen/src/Eigenvalues/Tridiagonalization.h \ 
        $$PWD/Eigen/src/Geometry/AlignedBox.h \ 
        $$PWD/Eigen/src/Geometry/AngleAxis.h \ 
        $$PWD/Eigen/src/Geometry/EulerAngles.h \ 
        $$PWD/Eigen/src/Geometry/Homogeneous.h \ 
        $$PWD/Eigen/src/Geometry/Hyperplane.h \ 
        $$PWD/Eigen/src/Geometry/OrthoMethods.h \ 
        $$PWD/Eigen/src/Geometry/ParametrizedLine.h \ 
        $$PWD/Eigen/src/Geometry/Quaternion.h \ 
        $$PWD/Eigen/src/Geometry/Rotation2D.h \ 
        $$PWD/Eigen/src/Geometry/RotationBase.h \ 
        $$PWD/Eigen/src/Geometry/Scaling.h \ 
        $$PWD/Eigen/src/Geometry/Transform.h \ 
        $$PWD/Eigen/src/Geometry/Translation.h \ 
        $$PWD/Eigen/src/Geometry/Umeyama.h \ 
        $$PWD/Eigen/src/Geometry/arch/Geometry_SSE.h \ 
        $$PWD/Eigen/src/Householder/BlockHouseholder.h \ 
        $$PWD/Eigen/src/Householder/Householder.h \ 
        $$PWD/Eigen/src/Householder/HouseholderSequence.h \ 
        $$PWD/Eigen/src/IterativeLinearSolvers/BasicPreconditioners.h \ 
        $$PWD/Eigen/src/IterativeLinearSolvers/BiCGSTAB.h \ 
        $$PWD/Eigen/src/IterativeLinearSolvers/ConjugateGradient.h \ 
        $$PWD/Eigen/src/IterativeLinearSolvers/IncompleteCholesky.h \ 
        $$PWD/Eigen/src/IterativeLinearSolvers/IncompleteLUT.h \ 
        $$PWD/Eigen/src/IterativeLinearSolvers/IterativeSolverBase.h \ 
        $$PWD/Eigen/src/IterativeLinearSolvers/LeastSquareConjugateGradient.h \ 
        $$PWD/Eigen/src/IterativeLinearSolvers/SolveWithGuess.h \ 
        $$PWD/Eigen/src/Jacobi/Jacobi.h \ 
        $$PWD/Eigen/src/LU/Determinant.h \ 
        $$PWD/Eigen/src/LU/FullPivLU.h \ 
        $$PWD/Eigen/src/LU/InverseImpl.h \ 
        $$PWD/Eigen/src/LU/PartialPivLU.h \ 
        $$PWD/Eigen/src/LU/PartialPivLU_LAPACKE.h \ 
        $$PWD/Eigen/src/LU/arch/Inverse_SSE.h \ 
        $$PWD/Eigen/src/MetisSupport/MetisSupport.h \ 
        $$PWD/Eigen/src/misc/blas.h \ 
        $$PWD/Eigen/src/misc/Image.h \ 
        $$PWD/Eigen/src/misc/Kernel.h \ 
        $$PWD/Eigen/src/misc/lapack.h \ 
        $$PWD/Eigen/src/misc/lapacke.h \ 
        $$PWD/Eigen/src/misc/lapacke_mangling.h \ 
        $$PWD/Eigen/src/misc/RealSvd2x2.h \ 
        $$PWD/Eigen/src/OrderingMethods/Amd.h \ 
        $$PWD/Eigen/src/OrderingMethods/Eigen_Colamd.h \ 
        $$PWD/Eigen/src/OrderingMethods/Ordering.h \ 
        $$PWD/Eigen/src/PardisoSupport/PardisoSupport.h \ 
        $$PWD/Eigen/src/PaStiXSupport/PaStiXSupport.h \ 
        $$PWD/Eigen/src/plugins/ArrayCwiseBinaryOps.h \ 
        $$PWD/Eigen/src/plugins/ArrayCwiseUnaryOps.h \ 
        $$PWD/Eigen/src/plugins/BlockMethods.h \ 
        $$PWD/Eigen/src/plugins/CommonCwiseBinaryOps.h \ 
        $$PWD/Eigen/src/plugins/CommonCwiseUnaryOps.h \ 
        $$PWD/Eigen/src/plugins/MatrixCwiseBinaryOps.h \ 
        $$PWD/Eigen/src/plugins/MatrixCwiseUnaryOps.h \ 
        $$PWD/Eigen/src/QR/ColPivHouseholderQR.h \ 
        $$PWD/Eigen/src/QR/ColPivHouseholderQR_LAPACKE.h \ 
        $$PWD/Eigen/src/QR/CompleteOrthogonalDecomposition.h \ 
        $$PWD/Eigen/src/QR/FullPivHouseholderQR.h \ 
        $$PWD/Eigen/src/QR/HouseholderQR.h \ 
        $$PWD/Eigen/src/QR/HouseholderQR_LAPACKE.h \ 
        $$PWD/Eigen/src/SparseCholesky/SimplicialCholesky.h \ 
        $$PWD/Eigen/src/SparseCholesky/SimplicialCholesky_impl.h \ 
        $$PWD/Eigen/src/SparseCore/AmbiVector.h \ 
        $$PWD/Eigen/src/SparseCore/CompressedStorage.h \ 
        $$PWD/Eigen/src/SparseCore/ConservativeSparseSparseProduct.h \ 
        $$PWD/Eigen/src/SparseCore/MappedSparseMatrix.h \ 
        $$PWD/Eigen/src/SparseCore/SparseAssign.h \ 
        $$PWD/Eigen/src/SparseCore/SparseBlock.h \ 
        $$PWD/Eigen/src/SparseCore/SparseColEtree.h \ 
        $$PWD/Eigen/src/SparseCore/SparseCompressedBase.h \ 
        $$PWD/Eigen/src/SparseCore/SparseCwiseBinaryOp.h \ 
        $$PWD/Eigen/src/SparseCore/SparseCwiseUnaryOp.h \ 
        $$PWD/Eigen/src/SparseCore/SparseDenseProduct.h \ 
        $$PWD/Eigen/src/SparseCore/SparseDiagonalProduct.h \ 
        $$PWD/Eigen/src/SparseCore/SparseDot.h \ 
        $$PWD/Eigen/src/SparseCore/SparseFuzzy.h \ 
        $$PWD/Eigen/src/SparseCore/SparseMap.h \ 
        $$PWD/Eigen/src/SparseCore/SparseMatrix.h \ 
        $$PWD/Eigen/src/SparseCore/SparseMatrixBase.h \ 
        $$PWD/Eigen/src/SparseCore/SparsePermutation.h \ 
        $$PWD/Eigen/src/SparseCore/SparseProduct.h \ 
        $$PWD/Eigen/src/SparseCore/SparseRedux.h \ 
        $$PWD/Eigen/src/SparseCore/SparseRef.h \ 
        $$PWD/Eigen/src/SparseCore/SparseSelfAdjointView.h \ 
        $$PWD/Eigen/src/SparseCore/SparseSolverBase.h \ 
        $$PWD/Eigen/src/SparseCore/SparseSparseProductWithPruning.h \ 
        $$PWD/Eigen/src/SparseCore/SparseTranspose.h \ 
        $$PWD/Eigen/src/SparseCore/SparseTriangularView.h \ 
        $$PWD/Eigen/src/SparseCore/SparseUtil.h \ 
        $$PWD/Eigen/src/SparseCore/SparseVector.h \ 
        $$PWD/Eigen/src/SparseCore/SparseView.h \ 
        $$PWD/Eigen/src/SparseCore/TriangularSolver.h \ 
        $$PWD/Eigen/src/SparseLU/SparseLU.h \ 
        $$PWD/Eigen/src/SparseLU/SparseLUImpl.h \ 
        $$PWD/Eigen/src/SparseLU/SparseLU_column_bmod.h \ 
        $$PWD/Eigen/src/SparseLU/SparseLU_column_dfs.h \ 
        $$PWD/Eigen/src/SparseLU/SparseLU_copy_to_ucol.h \ 
        $$PWD/Eigen/src/SparseLU/SparseLU_gemm_kernel.h \ 
        $$PWD/Eigen/src/SparseLU/SparseLU_heap_relax_snode.h \ 
        $$PWD/Eigen/src/SparseLU/SparseLU_kernel_bmod.h \ 
        $$PWD/Eigen/src/SparseLU/SparseLU_Memory.h \ 
        $$PWD/Eigen/src/SparseLU/SparseLU_panel_bmod.h \ 
        $$PWD/Eigen/src/SparseLU/SparseLU_panel_dfs.h \ 
        $$PWD/Eigen/src/SparseLU/SparseLU_pivotL.h \ 
        $$PWD/Eigen/src/SparseLU/SparseLU_pruneL.h \ 
        $$PWD/Eigen/src/SparseLU/SparseLU_relax_snode.h \ 
        $$PWD/Eigen/src/SparseLU/SparseLU_Structs.h \ 
        $$PWD/Eigen/src/SparseLU/SparseLU_SupernodalMatrix.h \ 
        $$PWD/Eigen/src/SparseLU/SparseLU_Utils.h \ 
        $$PWD/Eigen/src/SparseQR/SparseQR.h \ 
        $$PWD/Eigen/src/SPQRSupport/SuiteSparseQRSupport.h \ 
        $$PWD/Eigen/src/StlSupport/details.h \ 
        $$PWD/Eigen/src/StlSupport/StdDeque.h \ 
        $$PWD/Eigen/src/StlSupport/StdList.h \ 
        $$PWD/Eigen/src/StlSupport/StdVector.h \ 
        $$PWD/Eigen/src/SuperLUSupport/SuperLUSupport.h \ 
        $$PWD/Eigen/src/SVD/BDCSVD.h \ 
        $$PWD/Eigen/src/SVD/JacobiSVD.h \ 
        $$PWD/Eigen/src/SVD/JacobiSVD_LAPACKE.h \ 
        $$PWD/Eigen/src/SVD/SVDBase.h \ 
        $$PWD/Eigen/src/SVD/UpperBidiagonalization.h \ 
        $$PWD/Eigen/src/UmfPackSupport/UmfPackSupport.h \ 
 
    QXPACK_IC_HEADERS_COPY += $${QXPACK_IC_HEADERS_ALGOR_3RD_EIGEN} 
           $$PWD/qxpack_ic_algor_3rd_eigen.pri 

    HEADERS += \ 
        # $${QXPACK_IC_HEADERS_ALGOR_3RD_EIGEN}\ 

    message( qxpack_indcom_algor_thr_eigen include as headers ) 
} 
